name: Build and Push to ECR
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: AWS ECR
      # You may pin to the exact commit or the version.
      # uses: kciter/aws-ecr-action@79255b7c5aa03dbf6d7c46cff2bfd049874cd98d
      uses: kciter/aws-ecr-action@v4
      with:
        # The AWS access key id
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # The AWS secret access key
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # AWS Account ID
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        # A role to assume under the account_id account.
        # Name of your ECR repository
        repo: happy
        # The AWS region
        region: us-east-1
        tags: latest
        # Images to use as cache for the docker build (see `--cache-from` argument docs.docker.com/engine/reference/commandline/build)
              
